---
title: "Evidencia 1 | Analisis Exploratorio de los datos"
author: "Daniella Estela Sánchez Hernández A00845754, Andres Rodriguez Cantu A01287002, Isabella Anaís De la Garza Almazán A01663196"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
bibliography: src/references.bib
csl: src/apa.csl
link-citations: true
knit: (function(input, encoding) rmarkdown::render(input, encoding = encoding, output_dir = "output", envir = new.env()))


output:
 html_document:
  toc: true
  toc_float: true
  theme: journal
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)

library(stringi) # manejo de caracteres especiales
```

```{r, include=FALSE}
# Establece el wd al path en donde se esta knitteando el documento
# Si se corre esto mientras no se esta knitteando, aparecera un error.
rmd_path <- knitr::current_input()
if (nzchar(rmd_path)) {
  setwd(normalizePath(dirname(rmd_path)))
} else if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
}
```

# PARTE I
## 1. Las variables y datos t
```{r child='src/inciso1.rmd'}
```

## 2. Comprensión inicial del fenómeno y definición del objetivo de indagación
```{r child='src/inciso2.rmd'}
```

## 3. Selección y justificación de variables
```{r child='src/inciso3.rmd'}
```

## 4. Análisis Estadístico de los datos comparativo por región
```{r child='src/inciso4.rmd'}
```

## 5. Interpretación de resultados en el contexto
```{r child='src/inciso5.rmd'}
```


# Referencias