### 8.1 Hipótesis 1: Oxígeno disuelto por zona de profundidad

```{r echo=FALSE}
means_depth <- tapply(datosEq1$mean_O2ml_L, datosEq1$Depth_zone, mean)
n_depth <- tapply(datosEq1$mean_O2ml_L, datosEq1$Depth_zone, length)
sd_depth <- tapply(datosEq1$mean_O2ml_L, datosEq1$Depth_zone, sd)
ci_depth <- qnorm(0.975) * sd_depth / sqrt(n_depth)

lower_depth <- means_depth - ci_depth
upper_depth <- means_depth + ci_depth

par(mar = c(5, 8, 4, 2) + 0.1)
plot("", ylim = c(0.5, 4.5), xlim = c(1.5, 6.2), yaxt = "n",
     ylab = "", xlab = "Oxígeno disuelto medio (mL/L)",
     main = "Intervalos de confianza del 95% para la media\nde oxígeno disuelto por zona de profundidad")
axis(2, at = 4:1, labels = names(means_depth), las = 1)

for (i in 1:4) {
  y <- 4 - i + 1
  arrows(lower_depth[i], y, upper_depth[i], y,
         angle = 90, code = 3, length = 0.08, lwd = 2, col = "blue")
  points(means_depth[i], y, pch = 19, cex = 1.2, col = "red")
}
abline(v = 5, col = "gray40", lty = 2, lwd = 1.5)
text(5, 0.7, "Umbral óptimo (5 mL/L)", cex = 0.7, col = "gray40", xpd = TRUE)
```

### 8.2 Hipótesis 2: Oxígeno disuelto por clase de densidad del agua

```{r echo=FALSE}
means_dens <- tapply(datosEq1$mean_O2ml_L, datosEq1$Water_density_class, mean)
n_dens <- tapply(datosEq1$mean_O2ml_L, datosEq1$Water_density_class, length)
sd_dens <- tapply(datosEq1$mean_O2ml_L, datosEq1$Water_density_class, sd)
ci_dens <- qnorm(0.975) * sd_dens / sqrt(n_dens)

lower_dens <- means_dens - ci_dens
upper_dens <- means_dens + ci_dens

par(mar = c(5, 8, 4, 2) + 0.1)
plot("", ylim = c(0.5, 3.5), xlim = c(0.5, 6.2), yaxt = "n",
     ylab = "", xlab = "Oxígeno disuelto medio (mL/L)",
     main = "Intervalos de confianza del 95% para la media\nde oxígeno disuelto por clase de densidad")
axis(2, at = 3:1, labels = names(means_dens), las = 1)

for (i in 1:3) {
  y <- 3 - i + 1
  arrows(lower_dens[i], y, upper_dens[i], y,
         angle = 90, code = 3, length = 0.08, lwd = 2, col = "blue")
  points(means_dens[i], y, pch = 19, cex = 1.2, col = "red")
}
abline(v = 5, col = "gray40", lty = 2, lwd = 1.5)
text(5, 0.5, "Umbral óptimo (5 mL/L)", cex = 0.7, col = "gray40", xpd = TRUE)
```
