### 5.1 Comparación entre variables númericas y variables categóricas
Las variables categóricas tienen evidentemente una correlación positiva de acuerdo a las variables numéricas. Esto se puede comprobar en el apartado [4.2](#4.2), sobre todo en el gráfico [4.2.3](#4.2.3). Gráfico en donde podemos ver que mientras más fosfatos hay en el agua, se vuelve más densa el agua. O bien, mientras más oxígeno disuelto hay en el agua, el agua es menos densa. No nos debería de sorprender encontrar dichas correlaciones, al final del día, las variables categóricas se construyen a partir de los propios datos numéricos. 

### 5.2 Uso de medidas
Pongamos de ejemplo las variables que nos hablan directamente sobre la profundidad de la zona [4.3.5](#4.3.5). Podemos ver que mientras más profunda es el agua, se encuentra menos oxígeno disuelto; la temperatura decrece y los fosfatos suben. Fundamentando aún más esta idea con la densidad del agua [4.3.6](#4.3.6), es fácil de visualizar que mientras más densidad tiene el agua, la propia agua contiene una cantidad y saturación de oxígeno menor a la de si la densidad del agua fuera ligera; además de contener mucha menos clorofila-a que en áreas menos densas.


### 5.3 Interpretación de datos  
Con las gráficas, podemos visualizar que dependiendo del ambiente, ciertas zonas experimentan ciertas condiciones ambientales muy variadas; inusualmente variadas. Observando las figuras de [4.3.6](#4.3.6), podemos ver que en la cantidad de clorofila-a es muy variable; conteniendo extremos cuando la densidad del agua es baja o intermedia. O bien, en [4.3.5](#4.3.5) La cantidad de fosfatos por zona de profundidad varía bastante; hallando valores atípicos en algunas profundidades. Hay muchísimas variables de interés, la temperatura, la salinidad, la cantidad de fosfatos y clorofila-a son valores de extrema importancia. Un pequeño cambio en ellos es capaz de poner a todo el ecosistema en peligro; al no estar adaptados, la fauna termina desplazándose o extinguiéndose en dichas zonas. Evidentemente lo mejor de estos datos es tener más puntos de apoyo en el tiempo; con estos datos tenemos la idea que, cosas como la temperatura y la salinidad del agua están en crecimiento a un ritmo alarmante. Tan solo hace unas cuantas décadas, la temperatura del mar ha crecido más de un grado; el ritmo actual de incremento por década es alrededor de $0.27^{\circ}\text{C}$. Estos tipos de datos y patrones nos hacen entender que estos problemas son problemas que hoy nos están afectando; que si no hacemos algo, la fauna marina decrece y se desplaza; entre otras cosas, perjudicando la pesca, la exploración marítima y exterminando a la biodiversidad marina.

### 5.4 Formulación de preguntas que inicializo la situación problema.
A partir de nuestra interpretación, podemos confirmar el enunciado inicial de la situación problema: _El océano cambia, los datos lo revelan_. Pero estos cambios cómo pueden estar para bien, también pueden estar para mal. Dentro de estos cambios, nosotros queremos dar enfoque en tres preguntas que definirán las siguientes etapas de la situación problema. 

- ¿De qué manera las variaciones e incrementos alarmantes en la temperatura y la salinidad del agua en las últimas décadas ponen en riesgo el equilibrio del ecosistema y la biodiversidad marina?

- ¿Qué impacto tienen los valores atípicos y las condiciones ambientales inusualmente variadas de clorofila-a y fosfatos en las actividades humanas como la pesca y la exploración marítima?

- ¿En qué medida la disminución del oxígeno disuelto y de la clorofila-a en las zonas con mayor densidad de agua funciona como un indicador del deterioro o transformación drástica de un ecosistema marino específico?
Usando estas preguntas, queremos encontrar respuestas acerca del origen de los datos. No necesariamente por una falta de validez, si no para ver cómo estas variables locales afectan a todo el ecosistema global; indagando no sólo en la rigidez de los datos, sino en plantear un origen de la problemática y con ello una posible solución.

Usando estas preguntas, queremos encontrar respuestas acerca del origen de los datos. No necesariamente por una falta de validez, sino para ver cómo estas variables locales afectan a todo el ecosistema global; indagando no sólo en la rigidez de los datos, sino en plantear un origen de la problemática y con ello una posible solución.
